{{- if and .Values.webhook.enabled .Values.webhook.certManager.enabled }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ include "authentik-envoy-operator.fullname" . }}-webhook
  labels:
    {{- include "authentik-envoy-operator.labels" . | nindent 4 }}
spec:
  secretName: {{ include "authentik-envoy-operator.fullname" . }}-webhook-tls
  dnsNames:
    - {{ include "authentik-envoy-operator.fullname" . }}-webhook.{{ .Release.Namespace }}.svc
    - {{ include "authentik-envoy-operator.fullname" . }}-webhook.{{ .Release.Namespace }}.svc.cluster.local
  {{- if .Values.webhook.certManager.issuerRef.name }}
  issuerRef:
    name: {{ .Values.webhook.certManager.issuerRef.name }}
    kind: {{ .Values.webhook.certManager.issuerRef.kind | default "ClusterIssuer" }}
  {{- else }}
  issuerRef:
    name: {{ include "authentik-envoy-operator.fullname" . }}-selfsigned
    kind: Issuer
  {{- end }}
---
{{- if not .Values.webhook.certManager.issuerRef.name }}
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: {{ include "authentik-envoy-operator.fullname" . }}-selfsigned
  labels:
    {{- include "authentik-envoy-operator.labels" . | nindent 4 }}
spec:
  selfSigned: {}
{{- end }}
{{- end }}
