---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - authentik-envoy-operator.io
  resources:
  - authentikproviders
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - authentik-envoy-operator.io
  resources:
  - authentikproviders/status
  - oidcpolicies/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - authentik-envoy-operator.io
  resources:
  - oidcpolicies
  verbs:
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - authentik-envoy-operator.io
  resources:
  - oidcpolicies/finalizers
  verbs:
  - update
- apiGroups:
  - gateway.envoyproxy.io
  resources:
  - securitypolicies
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - gateway.networking.k8s.io
  resources:
  - httproutes
  verbs:
  - get
  - list
  - watch
