apiVersion: authentik-envoy-operator.io/v1alpha1
kind: AuthentikProvider
metadata:
  name: main
spec:
  host: "https://authentik.example.com"
  apiTokenSecretRef:
    name: authentik-api-token
    namespace: authentik-system
    key: token
  authorizationFlowSlug: "default-provider-authorization-implicit-consent"
  invalidationFlowSlug: "default-provider-invalidation-flow"
