apiVersion: authentik-envoy-operator.io/v1alpha1
kind: OIDCPolicy
metadata:
  name: grafana-oidc
  namespace: monitoring
spec:
  providerRef:
    name: main
  targetRefs:
    - name: grafana-route
  oidc:
    allowedGroups:
      - admins
      - developers
    signingKey: "authentik Self-signed Certificate"
    propertyMappings:
      - "authentik default OAuth Mapping: OpenID 'openid'"
      - "authentik default OAuth Mapping: OpenID 'profile'"
      - "authentik default OAuth Mapping: OpenID 'email'"
    scopes:
      - openid
      - profile
      - email
    forwardAccessToken: true
